//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api___Angular___Crud_Operation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int blogId { get; set; }
        public string blogTitle { get; set; }
        public byte[] blogTimePosted { get; set; }
        public string blogContent { get; set; }
        public int adminId { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
