//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api___Angular___Crud_Operation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int usertId { get; set; }
        public string userName { get; set; }
        public string userEmail { get; set; }
        public string country { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
